--
--  List of world's countries containing the official short names in English as given by ISO 3166-1,
--  the ISO 3166-1-alpha-2 code provided by the International Organization for Standardization
--  (http://www.iso.org/iso/prods-services/iso3166ma/02iso-3166-code-lists/country_names_and_code_elements)
--  and the ISO alpha-3 code provided by the United Nations Statistics Division
--  (http://unstats.un.org/unsd/methods/m49/m49alpha.htm)
--
--  compiled by Stefan Gabos
--  version 1.2.1 (last revision: January 27, 2016)
--  version 1.2.2 (last revision: Februrary 09, 2017) added numeric iso codes by @kixe
--  version 1.2.3 (last revision: Februrary 12, 2017) added german translations if different by @kixe
--  version 1.2.4 (last revision: March 04, 2017) added table continents by @kixe
--
--  Continents listed by size:
--  1 : Asia (AS)
--  2 : Africa (AF)
--  3 : North America (NA)
--  4 : South America (SA)
--  5 : Antarctica (AN)
--  6 : Europe (EU)
--  7 : Oceania (OC)
--  Each country has an assigned continent index number
--
--  http://stefangabos.ro/other-projects/list-of-world-countries-with-national-flags/
--
-- Adminer 4.2.5 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `countries`;
DROP TABLE IF EXISTS `continents`;

CREATE TABLE IF NOT EXISTS `continents` (
  `id` int(1) NOT NULL AUTO_INCREMENT COMMENT 'Index by size',
  `code` CHAR(2) NOT NULL COMMENT 'Continent code',
  `name` VARCHAR(255),
  PRIMARY KEY (`id`,`code`)
) ENGINE=InnoDB;

INSERT INTO `continents` (`code`, `name`) VALUES
  ('AS', 'Asia'),
  ('AF', 'Africa'),
  ('NA', 'North America'),
  ('SA', 'South America'),
  ('AN', 'Antarctica'),
  ('EU', 'Europe'),
  ('OC', 'Oceania');
  
   
CREATE TABLE `countries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `numeric` smallint(3) unsigned zerofill NOT NULL DEFAULT '000',
  `alpha_2` varchar(2) NOT NULL DEFAULT '' COMMENT 'Two-letter country code (ISO 3166-1 alpha-2)',
  `alpha_3` varchar(3) NOT NULL DEFAULT '' COMMENT 'Three-letter country code (ISO 3166-1 alpha-3)',
  `continent` smallint(1) NOT NULL DEFAULT '0' COMMENT 'Continent index based on 7 continents ranked by size',
  `name_en` varchar(255) NOT NULL DEFAULT '' COMMENT 'English country name',
  `name_de` varchar(255) NOT NULL DEFAULT '' COMMENT 'German country name',
  PRIMARY KEY (`id`, `alpha_2`),
  KEY `continent` (`continent`),
  CONSTRAINT `fk_countries_continents` FOREIGN KEY (`continent`) REFERENCES `continents` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `countries` (`id`, `numeric`, `alpha_2`, `alpha_3`, `name_en`, `name_de`) VALUES
(1,	004,	'af',	'afg',	'Afghanistan',	'Afghanistan'),
(2,	248,	'ax',	'ala',	'Aland Islands',	'Åland'),
(3,	008,	'al',	'alb',	'Albania',	'Albanien'),
(4,	012,	'dz',	'dza',	'Algeria',	'Algerien'),
(5,	016,	'as',	'asm',	'American Samoa',	'Amerikanisch-Samoa'),
(6,	020,	'ad',	'and',	'Andorra',	''),
(7,	024,	'ao',	'ago',	'Angola',	''),
(8,	660,	'ai',	'aia',	'Anguilla',	''),
(9,	010,	'aq',	'ata',	'Antarctica',	'Antarktis'),
(10,	028,	'ag',	'atg',	'Antigua and Barbuda',	'Antigua und Barbuda'),
(11,	032,	'ar',	'arg',	'Argentina',	'Argentinien'),
(12,	051,	'am',	'arm',	'Armenia',	'Armenien'),
(13,	533,	'aw',	'abw',	'Aruba',	''),
(14,	036,	'au',	'aus',	'Australia',	'Australien'),
(15,	040,	'at',	'aut',	'Austria',	'Österreich'),
(16,	031,	'az',	'aze',	'Azerbaijan',	'Aserbaidschan'),
(17,	044,	'bs',	'bhs',	'Bahamas',	''),
(18,	048,	'bh',	'bhr',	'Bahrain',	''),
(19,	050,	'bd',	'bgd',	'Bangladesh',	'Bangladesch'),
(20,	052,	'bb',	'brb',	'Barbados',	''),
(21,	112,	'by',	'blr',	'Belarus',	'Weißrußland (Belarus)'),
(22,	056,	'be',	'bel',	'Belgium',	'Belgien'),
(23,	084,	'bz',	'blz',	'Belize',	''),
(24,	204,	'bj',	'ben',	'Benin',	''),
(25,	060,	'bm',	'bmu',	'Bermuda',	''),
(26,	064,	'bt',	'btn',	'Bhutan',	''),
(27,	068,	'bo',	'bol',	'Bolivia, Plurinational State of',	'Bolivien'),
(28,	535,	'bq',	'bes',	'Bonaire, Sint Eustatius and Saba',	''),
(29,	070,	'ba',	'bih',	'Bosnia and Herzegovina',	'Bosnien und Herzegovina'),
(30,	072,	'bw',	'bwa',	'Botswana',	''),
(31,	074,	'bv',	'bvt',	'Bouvet Island',	'Bouvetinsel'),
(32,	076,	'br',	'bra',	'Brazil',	'Brasilien'),
(33,	086,	'io',	'iot',	'British Indian Ocean Territory',	'Britisches Territorium im Indischen Ozean'),
(34,	096,	'bn',	'brn',	'Brunei Darussalam',	''),
(35,	100,	'bg',	'bgr',	'Bulgaria',	''),
(36,	854,	'bf',	'bfa',	'Burkina Faso',	''),
(37,	108,	'bi',	'bdi',	'Burundi',	''),
(38,	116,	'kh',	'khm',	'Cambodia',	'Kambodscha'),
(39,	120,	'cm',	'cmr',	'Cameroon',	'Kamerun'),
(40,	124,	'ca',	'can',	'Canada',	'Kanada'),
(41,	132,	'cv',	'cpv',	'Cape Verde',	'Kap Verde'),
(42,	136,	'ky',	'cym',	'Cayman Islands',	'Kaimaninseln'),
(43,	140,	'cf',	'caf',	'Central African Republic',	'Zentralafrikanische Republik'),
(44,	148,	'td',	'tcd',	'Chad',	'Tschad'),
(45,	152,	'cl',	'chl',	'Chile',	''),
(46,	156,	'cn',	'chn',	'China',	''),
(47,	162,	'cx',	'cxr',	'Christmas Island',	'Weihnachtsinsel'),
(48,	166,	'cc',	'cck',	'Cocos (Keeling) Islands',	'Kokosinseln (Keeling)'),
(49,	170,	'co',	'col',	'Colombia',	'Kolumbien'),
(50,	174,	'km',	'com',	'Comoros',	'Komoren'),
(51,	178,	'cg',	'cog',	'Congo',	'Kongo'),
(52,	180,	'cd',	'cod',	'Congo, The Democratic Republic of the',	'Demokratische Republik Kongo'),
(53,	184,	'ck',	'cok',	'Cook Islands',	'Cookinseln'),
(54,	188,	'cr',	'cri',	'Costa Rica',	''),
(55,	384,	'ci',	'civ',	'Cote d\'Ivoire',	'Côte d\'Ivoire (Elfenbeinküste)'),
(56,	191,	'hr',	'hrv',	'Croatia',	'Kroatien'),
(57,	192,	'cu',	'cub',	'Cuba',	'Kuba'),
(58,	531,	'cw',	'cuw',	'Curacao',	'Curaçao'),
(59,	196,	'cy',	'cyp',	'Cyprus',	'Zypern'),
(60,	203,	'cz',	'cze',	'Czech Republic',	'Tschechien (Tschechische Republik)'),
(61,	208,	'dk',	'dnk',	'Denmark',	'Dänemark'),
(62,	262,	'dj',	'dji',	'Djibouti',	''),
(63,	212,	'dm',	'dma',	'Dominica',	''),
(64,	214,	'do',	'dom',	'Dominican Republic',	'Dominikanische Republik'),
(65,	218,	'ec',	'ecu',	'Ecuador',	''),
(66,	818,	'eg',	'egy',	'Egypt',	'Ägypten'),
(67,	222,	'sv',	'slv',	'El Salvador',	''),
(68,	226,	'gq',	'gnq',	'Equatorial Guinea',	'Äquatorialguinea'),
(69,	232,	'er',	'eri',	'Eritrea',	''),
(70,	233,	'ee',	'est',	'Estonia',	'Estland'),
(71,	231,	'et',	'eth',	'Ethiopia',	'Äthiopien'),
(72,	238,	'fk',	'flk',	'Falkland Islands (Malvinas)',	'Falklandinseln (Malvinen)'),
(73,	234,	'fo',	'fro',	'Faroe Islands',	'Färöer (Färöer-Inseln)'),
(74,	242,	'fj',	'fji',	'Fiji',	'Fidschi'),
(75,	246,	'fi',	'fin',	'Finland',	'Finnland'),
(76,	250,	'fr',	'fra',	'France',	'Frankreich'),
(77,	254,	'gf',	'guf',	'French Guiana',	'Französisch-Guayana'),
(78,	258,	'pf',	'pyf',	'French Polynesia',	'Französisch-Polynesien'),
(79,	260,	'tf',	'atf',	'French Southern Territories',	'Französische Süd- und Antarktisgebiete'),
(80,	266,	'ga',	'gab',	'Gabon',	'Gabun'),
(81,	270,	'gm',	'gmb',	'Gambia',	''),
(82,	268,	'ge',	'geo',	'Georgia',	'Georgien'),
(83,	276,	'de',	'deu',	'Germany',	'Deutschland'),
(84,	288,	'gh',	'gha',	'Ghana',	''),
(85,	292,	'gi',	'gib',	'Gibraltar',	''),
(86,	300,	'gr',	'grc',	'Greece',	'Griechenland'),
(87,	304,	'gl',	'grl',	'Greenland',	'Grönland'),
(88,	308,	'gd',	'grd',	'Grenada',	''),
(89,	312,	'gp',	'glp',	'Guadeloupe',	''),
(90,	316,	'gu',	'gum',	'Guam',	''),
(91,	320,	'gt',	'gtm',	'Guatemala',	''),
(92,	831,	'gg',	'ggy',	'Guernsey',	''),
(93,	324,	'gn',	'gin',	'Guinea',	''),
(94,	624,	'gw',	'gnb',	'Guinea-Bissau',	''),
(95,	328,	'gy',	'guy',	'Guyana',	''),
(96,	332,	'ht',	'hti',	'Haiti',	''),
(97,	334,	'hm',	'hmd',	'Heard Island and McDonald Islands',	'Heard und Mcdonaldinseln'),
(98,	336,	'va',	'vat',	'Holy See (Vatican City State)',	'Heiliger Stuhl (Vatikanstadt)'),
(99,	340,	'hn',	'hnd',	'Honduras',	''),
(100,	344,	'hk',	'hkg',	'Hong Kong',	'Hongkong'),
(101,	348,	'hu',	'hun',	'Hungary',	'Ungarn'),
(102,	352,	'is',	'isl',	'Iceland',	'Island'),
(103,	356,	'in',	'ind',	'India',	'Indien'),
(104,	360,	'id',	'idn',	'Indonesia',	'Indonesien'),
(105,	364,	'ir',	'irn',	'Iran, Islamic Republic of',	'Iran, Islamische Republik'),
(106,	368,	'iq',	'irq',	'Iraq',	'Irak'),
(107,	372,	'ie',	'irl',	'Ireland',	'Irland'),
(108,	833,	'im',	'imn',	'Isle of Man',	'Insel Man'),
(109,	376,	'il',	'isr',	'Israel',	''),
(110,	380,	'it',	'ita',	'Italy',	'Italien'),
(111,	388,	'jm',	'jam',	'Jamaica',	'Jamaika'),
(112,	392,	'jp',	'jpn',	'Japan',	''),
(113,	832,	'je',	'jey',	'Jersey',	''),
(114,	400,	'jo',	'jor',	'Jordan',	'Jordanien'),
(115,	398,	'kz',	'kaz',	'Kazakhstan',	'Kasachstan'),
(116,	404,	'ke',	'ken',	'Kenya',	''),
(117,	296,	'ki',	'kir',	'Kiribati',	''),
(118,	408,	'kp',	'prk',	'Korea, Democratic People\'s Republic of',	'Korea, Demokratische Volksrepublik (Nord Korea)'),
(119,	410,	'kr',	'kor',	'Korea, Republic of',	'Korea, Republik (Süd Korea)'),
(120,	414,	'kw',	'kwt',	'Kuwait',	''),
(121,	417,	'kg',	'kgz',	'Kyrgyzstan',	'Kirgisistan'),
(122,	418,	'la',	'lao',	'Lao People\'s Democratic Republic',	'Laos, Demokratische Volksrepublik'),
(123,	428,	'lv',	'lva',	'Latvia',	'Lettland'),
(124,	422,	'lb',	'lbn',	'Lebanon',	'Libanon'),
(125,	426,	'ls',	'lso',	'Lesotho',	''),
(126,	430,	'lr',	'lbr',	'Liberia',	''),
(127,	434,	'ly',	'lby',	'Libyan Arab Jamahiriya',	'Libyen'),
(128,	438,	'li',	'lie',	'Liechtenstein',	''),
(129,	440,	'lt',	'ltu',	'Lithuania',	'Litauen'),
(130,	442,	'lu',	'lux',	'Luxembourg',	'Luxemburg'),
(131,	446,	'mo',	'mac',	'Macao',	'Macau'),
(132,	807,	'mk',	'mkd',	'Macedonia, The former Yugoslav Republic of',	'Mazedonien'),
(133,	450,	'mg',	'mdg',	'Madagascar',	'Madagaskar'),
(134,	454,	'mw',	'mwi',	'Malawi',	''),
(135,	458,	'my',	'mys',	'Malaysia',	''),
(136,	462,	'mv',	'mdv',	'Maldives',	'Malediven'),
(137,	466,	'ml',	'mli',	'Mali',	''),
(138,	470,	'mt',	'mlt',	'Malta',	''),
(139,	504,	'mh',	'mhl',	'Marshall Islands',	'Marshallinseln'),
(140,	584,	'mq',	'mtq',	'Martinique',	''),
(141,	478,	'mr',	'mrt',	'Mauritania',	'Mauretanien'),
(142,	480,	'mu',	'mus',	'Mauritius',	''),
(143,	175,	'yt',	'myt',	'Mayotte',	''),
(144,	484,	'mx',	'mex',	'Mexico',	'Mexiko'),
(145,	583,	'fm',	'fsm',	'Micronesia, Federated States of',	'Mikronesien, Föderierte Staaten von'),
(146,	498,	'md',	'mda',	'Moldova, Republic of',	'Moldau, Republik'),
(147,	492,	'mc',	'mco',	'Monaco',	''),
(148,	496,	'mn',	'mng',	'Mongolia',	'Mongolei'),
(149,	499,	'me',	'mne',	'Montenegro',	''),
(150,	500,	'ms',	'msr',	'Montserrat',	''),
(151,	504,	'ma',	'mar',	'Morocco',	'Marokko'),
(152,	508,	'mz',	'moz',	'Mozambique',	'Mosambik'),
(153,	104,	'mm',	'mmr',	'Myanmar',	''),
(154,	516,	'na',	'nam',	'Namibia',	''),
(155,	520,	'nr',	'nru',	'Nauru',	''),
(156,	524,	'np',	'npl',	'Nepal',	''),
(157,	528,	'nl',	'nld',	'Netherlands',	'Niederlande'),
(158,	540,	'nc',	'ncl',	'New Caledonia',	'Neukaledonien'),
(159,	554,	'nz',	'nzl',	'New Zealand',	'Neuseeland'),
(160,	558,	'ni',	'nic',	'Nicaragua',	''),
(161,	562,	'ne',	'ner',	'Niger',	''),
(162,	566,	'ng',	'nga',	'Nigeria',	''),
(163,	570,	'nu',	'niu',	'Niue',	''),
(164,	574,	'nf',	'nfk',	'Norfolk Island',	'Norfolkinsel'),
(165,	580,	'mp',	'mnp',	'Northern Mariana Islands',	'Nördliche Marianen'),
(166,	578,	'no',	'nor',	'Norway',	'Norwegen'),
(167,	512,	'om',	'omn',	'Oman',	''),
(168,	586,	'pk',	'pak',	'Pakistan',	''),
(169,	585,	'pw',	'plw',	'Palau',	''),
(170,	275,	'ps',	'pse',	'Palestinian Territory, Occupied',	'Palästinensische Autonomiegebiete'),
(171,	591,	'pa',	'pan',	'Panama',	''),
(172,	598,	'pg',	'png',	'Papua New Guinea',	'Papua-Neuguinea'),
(173,	600,	'py',	'pry',	'Paraguay',	''),
(174,	604,	'pe',	'per',	'Peru',	''),
(175,	608,	'ph',	'phl',	'Philippines',	'Philippinen'),
(176,	612,	'pn',	'pcn',	'Pitcairn',	'Pitcairninseln'),
(177,	616,	'pl',	'pol',	'Poland',	'Polen'),
(178,	620,	'pt',	'prt',	'Portugal',	''),
(179,	630,	'pr',	'pri',	'Puerto Rico',	''),
(180,	634,	'qa',	'qat',	'Qatar',	'Katar'),
(181,	638,	're',	'reu',	'Reunion',	'Réunion'),
(182,	642,	'ro',	'rou',	'Romania',	'Rumänien'),
(183,	643,	'ru',	'rus',	'Russian Federation',	'Russische Föderation (Russland)'),
(184,	646,	'rw',	'rwa',	'Rwanda',	'Ruanda'),
(185,	652,	'bl',	'blm',	'Saint Barthelemy',	''),
(186,	654,	'sh',	'shn',	'Saint Helena, Ascension and Tristan Da Cunha',	'St. Helena'),
(187,	659,	'kn',	'kna',	'Saint Kitts and Nevis',	'St. Kitts und Nevis'),
(188,	662,	'lc',	'lca',	'Saint Lucia',	'St. Lucia'),
(189,	663,	'mf',	'maf',	'Saint Martin (French Part)',	'St. Martin (französischer Teil)'),
(190,	666,	'pm',	'spm',	'Saint Pierre and Miquelon',	'St. Pierre und Miquelon'),
(191,	670,	'vc',	'vct',	'Saint Vincent and The Grenadines',	'St. Vincent und die Grenadinen'),
(192,	882,	'ws',	'wsm',	'Samoa',	''),
(193,	674,	'sm',	'smr',	'San Marino',	''),
(194,	678,	'st',	'stp',	'Sao Tome and Principe',	'São Tomé und Príncipe'),
(195,	682,	'sa',	'sau',	'Saudi Arabia',	'Saudi-Arabien'),
(196,	686,	'sn',	'sen',	'Senegal',	''),
(197,	688,	'rs',	'srb',	'Serbia',	'Serbien'),
(198,	690,	'sc',	'syc',	'Seychelles',	'Seychellen'),
(199,	694,	'sl',	'sle',	'Sierra Leone',	''),
(200,	702,	'sg',	'sgp',	'Singapore',	'Singapur'),
(201,	534,	'sx',	'sxm',	'Sint Maarten (Dutch Part)',	'St. Martin (niederländischer Teil)'),
(202,	703,	'sk',	'svk',	'Slovakia',	'Slowakei'),
(203,	705,	'si',	'svn',	'Slovenia',	'Slowenien'),
(204,	090,	'sb',	'slb',	'Solomon Islands',	'Salomonen'),
(205,	706,	'so',	'som',	'Somalia',	''),
(206,	710,	'za',	'zaf',	'South Africa',	'Südafrika'),
(207,	239,	'gs',	'sgs',	'South Georgia and The South Sandwich Islands',	'Südgeorgien und die südlichen Sandwichinseln'),
(208,	728,	'ss',	'ssd',	'South Sudan',	'Südsudan'),
(209,	724,	'es',	'esp',	'Spain',	'Spanien'),
(210,	144,	'lk',	'lka',	'Sri Lanka',	''),
(211,	729,	'sd',	'sdn',	'Sudan',	''),
(212,	740,	'sr',	'sur',	'Suriname',	'Suriname'),
(213,	744,	'sj',	'sjm',	'Svalbard and Jan Mayen',	'Svalbard und Jan Mayen'),
(214,	748,	'sz',	'swz',	'Swaziland',	'Swasiland'),
(215,	752,	'se',	'swe',	'Sweden',	'Schweden'),
(216,	756,	'ch',	'che',	'Switzerland',	'Schweiz'),
(217,	760,	'sy',	'syr',	'Syrian Arab Republic',	'Syrien, Arabische Republik'),
(218,	158,	'tw',	'twn',	'Taiwan, Province of China',	'Taiwan'),
(219,	762,	'tj',	'tjk',	'Tajikistan',	'Tadschikistan'),
(220,	834,	'tz',	'tza',	'Tanzania, United Republic of',	'Tansania, Vereinigte Republik'),
(221,	764,	'th',	'tha',	'Thailand',	''),
(222,	626,	'tl',	'tls',	'Timor-Leste',	''),
(223,	768,	'tg',	'tgo',	'Togo',	''),
(224,	772,	'tk',	'tkl',	'Tokelau',	''),
(225,	776,	'to',	'ton',	'Tonga',	''),
(226,	780,	'tt',	'tto',	'Trinidad and Tobago',	'Trinidad und Tobago'),
(227,	788,	'tn',	'tun',	'Tunisia',	'Tunesien'),
(228,	792,	'tr',	'tur',	'Turkey',	'Türkei'),
(229,	795,	'tm',	'tkm',	'Turkmenistan',	''),
(230,	796,	'tc',	'tca',	'Turks and Caicos Islands',	'Turks- und Caicosinseln'),
(231,	798,	'tv',	'tuv',	'Tuvalu',	''),
(232,	800,	'ug',	'uga',	'Uganda',	''),
(233,	804,	'ua',	'ukr',	'Ukraine',	''),
(234,	784,	'ae',	'are',	'United Arab Emirates',	'Vereinigte Arabische Emirate'),
(235,	826,	'gb',	'gbr',	'United Kingdom',	'Großbritannien'),
(236,	840,	'us',	'usa',	'United States',	'Vereinigte Staaten (USA)'),
(237,	581,	'um',	'umi',	'United States Minor Outlying Islands',	'Kleinere Amerikanische Überseeinseln'),
(238,	858,	'uy',	'ury',	'Uruguay',	''),
(239,	860,	'uz',	'uzb',	'Uzbekistan',	'Usbekistan'),
(240,	548,	'vu',	'vut',	'Vanuatu',	''),
(241,	862,	've',	'ven',	'Venezuela, Bolivarian Republic of',	'Venezuela'),
(242,	704,	'vn',	'vnm',	'Viet Nam',	'Vietnam'),
(243,	092,	'vg',	'vgb',	'Virgin Islands, British',	'Britische Jungferninseln'),
(244,	850,	'vi',	'vir',	'Virgin Islands, U.S.',	'Amerikanische Jungferninseln'),
(245,	876,	'wf',	'wlf',	'Wallis and Futuna',	'Wallis und Futuna'),
(246,	732,	'eh',	'esh',	'Western Sahara',	'Westsahara'),
(247,	887,	'ye',	'yem',	'Yemen',	'Jemen'),
(248,	894,	'zm',	'zmb',	'Zambia',	'Sambia'),
(249,	716,	'zw',	'zwe',	'Zimbabwe',	'Simbabwe');

-- 2017-02-12 10:16:57
