--
--  List of world's countries containing the official short names in English as given by ISO 3166-1,
--  the ISO 3166-1-alpha-2 code provided by the International Organization for Standardization
--  (http://www.iso.org/iso/prods-services/iso3166ma/02iso-3166-code-lists/country_names_and_code_elements)
--  and the ISO alpha-3 code provided by the United Nations Statistics Division
--  (http://unstats.un.org/unsd/methods/m49/m49alpha.htm)
--
--  compiled by Stefan Gabos
--  version 1.2.1 (last revision: January 27, 2016)
--  version 1.2.2 (last revision: Februrary 09, 2017) added numeric iso codes by @kixe
--  version 1.2.3 (last revision: Februrary 12, 2017) added german translations if different by @kixe

--
--  http://stefangabos.ro/other-projects/list-of-world-countries-with-national-flags/
--

DROP TABLE IF EXISTS `countries`;
CREATE TABLE `countries` (
  `id` int(11) NOT NULL auto_increment,
  `numeric` smallint(3) ZEROFILL UNSIGNED NOT NULL default 0,
  `alpha_2` varchar(2) NOT NULL default '',
  `alpha_3` varchar(3) NOT NULL default '',
  `name_en` varchar(255) NOT NULL default '',
  `name_de` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `countries` (`name_de`,`name_en`, `alpha_2`, `alpha_3`, `numeric`) VALUES
    ('Afghanistan', 'Afghanistan', 'af', 'afg', 4 ),
    ('Åland', 'Aland Islands', 'ax', 'ala', 248),
    ('Albanien', 'Albania', 'al', 'alb', 8),
    ('Algerien', 'Algeria', 'dz', 'dza', 12),
    ('Amerikanisch-Samo', 'American Samoa', 'as', 'asm', 16),
    ('', 'Andorra', 'ad', 'and', 20),
    ('', 'Angola', 'ao', 'ago', 24),
    ('', 'Anguilla', 'ai', 'aia', 660),
    ('Antarktis', 'Antarctica', 'aq', 'ata', 10),
    ('Antigua und Barbuda', 'Antigua and Barbuda', 'ag', 'atg', 28),
    ('Argentinien', 'Argentina', 'ar', 'arg', 32),
    ('Armenien', 'Armenia', 'am', 'arm', 51),
    ('', 'Aruba', 'aw', 'abw', 533),
    ('Australien', 'Australia', 'au', 'aus', 36),
    ('Österreich', 'Austria', 'at', 'aut', 40),
    ('Aserbaidschan', 'Azerbaijan', 'az', 'aze', 31),
    ('', 'Bahamas', 'bs', 'bhs', 44),
    ('', 'Bahrain', 'bh', 'bhr', 48),
    ('Bangladesch', 'Bangladesh', 'bd', 'bgd', 50),
    ('', 'Barbados', 'bb', 'brb', 52),
    ('Weißrußland (Belarus)', 'Belarus', 'by', 'blr', 112),
    ('Belgien', 'Belgium', 'be', 'bel', 56),
    ('', 'Belize', 'bz', 'blz', 84),
    ('', 'Benin', 'bj', 'ben', 204),
    ('', 'Bermuda', 'bm', 'bmu', 60),
    ('', 'Bhutan', 'bt', 'btn', 64),
    ('Bolivien', 'Bolivia, Plurinational State of', 'bo', 'bol', 68),
    ('', 'Bonaire, Sint Eustatius and Saba', 'bq', 'bes', 535),
    ('Bosnien und Herzegovina', 'Bosnia and Herzegovina', 'ba', 'bih', 70),
    ('', 'Botswana', 'bw', 'bwa', 72),
    ('Bouvetinsel', 'Bouvet Island', 'bv', 'bvt', 74),
    ('Brasilien', 'Brazil', 'br', 'bra', 76),
    ('Britisches Territorium im Indischen Ozean', 'British Indian Ocean Territory', 'io', 'iot', 86),
    ('', 'Brunei Darussalam', 'bn', 'brn', 96),
    ('', 'Bulgaria', 'bg', 'bgr', 100),
    ('', 'Burkina Faso', 'bf', 'bfa', 854),
    ('', 'Burundi', 'bi', 'bdi', 108),
    ('Kambodscha', 'Cambodia', 'kh', 'khm', 116),
    ('Kamerun', 'Cameroon', 'cm', 'cmr', 120),
    ('Kanada', 'Canada', 'ca', 'can', 124),
    ('Kap Verde', 'Cape Verde', 'cv', 'cpv', 132),
    ('Kaimaninseln', 'Cayman Islands', 'ky', 'cym', 136),
    ('Zentralafrikanische Republik', 'Central African Republic', 'cf', 'caf', 140),
    ('Tschad', 'Chad', 'td', 'tcd', 148),
    ('', 'Chile', 'cl', 'chl', 152),
    ('', 'China', 'cn', 'chn', 156),
    ('Weihnachtsinsel', 'Christmas Island', 'cx', 'cxr', 162),
    ('Kokosinseln (Keeling)', 'Cocos (Keeling) Islands', 'cc', 'cck', 166),
    ('Kolumbien', 'Colombia', 'co', 'col', 170),
    ('Komoren', 'Comoros', 'km', 'com', 174),
    ('Kongo', 'Congo', 'cg', 'cog', 178),
    ('Demokratische Republik Kongo', 'Congo, The Democratic Republic of the', 'cd', 'cod', 180),
    ('Cookinseln', 'Cook Islands', 'ck', 'cok', 184),
    ('', 'Costa Rica', 'cr', 'cri', 188),
    ('Côte d\'Ivoire (Elfenbeinküste)', 'Cote d\'Ivoire', 'ci', 'civ', 384),
    ('Kroatien', 'Croatia', 'hr', 'hrv', 191),
    ('Kuba', 'Cuba', 'cu', 'cub', 192),
    ('', 'Curaçao', 'cw', 'cuw', 531),
    ('Zypern', 'Cyprus', 'cy', 'cyp', 196),
    ('Tschechien (Tschechische Republik)', 'Czech Republic', 'cz', 'cze', 203),
    ('Dänemark', 'Denmark', 'dk', 'dnk', 208),
    ('', 'Djibouti', 'dj', 'dji', 262),
    ('', 'Dominica', 'dm', 'dma', 212),
    ('Dominikanische Republik', 'Dominican Republic', 'do', 'dom', 214),
    ('', 'Ecuador', 'ec', 'ecu', 218),
    ('Ägypten', 'Egypt', 'eg', 'egy', 818),
    ('', 'El Salvador', 'sv', 'slv', 222),
    ('Äquatorialguinea', 'Equatorial Guinea', 'gq', 'gnq', 226),
    ('', 'Eritrea', 'er', 'eri', 232),
    ('Estland', 'Estonia', 'ee', 'est', 233),
    ('Äthiopien', 'Ethiopia', 'et', 'eth', 231),
    ('Falklandinseln (Malvinen)', 'Falkland Islands (Malvinas)', 'fk', 'flk', 238),
    ('Färöer (Färöer-Inseln)', 'Faroe Islands', 'fo', 'fro', 234),
    ('Fidschi', 'Fiji', 'fj', 'fji', 242),
    ('Finnland', 'Finland', 'fi', 'fin', 246),
    ('Frankreich', 'France', 'fr', 'fra', 250),
    ('Französisch-Guayana', 'French Guiana', 'gf', 'guf', 254),
    ('Französisch-Polynesien', 'French Polynesia', 'pf', 'pyf', 258),
    ('Französische Süd- und Antarktisgebiete', 'French Southern Territories', 'tf', 'atf', 260),
    ('Gabun', 'Gabon', 'ga', 'gab', 266),
    ('', 'Gambia', 'gm', 'gmb', 270),
    ('Georgien', 'Georgia', 'ge', 'geo', 268),
    ('Deutschland', 'Germany', 'de', 'deu', 276),
    ('', 'Ghana', 'gh', 'gha', 288),
    ('', 'Gibraltar', 'gi', 'gib', 292),
    ('Griechenland', 'Greece', 'gr', 'grc', 300),
    ('Grönland', 'Greenland', 'gl', 'grl', 304),
    ('', 'Grenada', 'gd', 'grd', 308),
    ('', 'Guadeloupe', 'gp', 'glp', 312),
    ('', 'Guam', 'gu', 'gum', 316),
    ('', 'Guatemala', 'gt', 'gtm', 320),
    ('', 'Guernsey', 'gg', 'ggy', 831),
    ('', 'Guinea', 'gn', 'gin', 324),
    ('', 'Guinea-Bissau', 'gw', 'gnb', 624),
    ('', 'Guyana', 'gy', 'guy', 328),
    ('', 'Haiti', 'ht', 'hti', 332),
    ('Heard und Mcdonaldinseln', 'Heard Island and McDonald Islands', 'hm', 'hmd', 334),
    ('Heiliger Stuhl (Vatikanstadt)', 'Holy See (Vatican City State)', 'va', 'vat', 336),
    ('', 'Honduras', 'hn', 'hnd', 340),
    ('Hongkong', 'Hong Kong', 'hk', 'hkg', 344),
    ('Ungarn', 'Hungary', 'hu', 'hun', 348),
    ('Island', 'Iceland', 'is', 'isl', 352),
    ('Indien', 'India', 'in', 'ind', 356),
    ('Indonesien', 'Indonesia', 'id', 'idn', 360),
    ('Iran, Islamische Republik', 'Iran, Islamic Republic of', 'ir', 'irn', 364),
    ('Irak', 'Iraq', 'iq', 'irq', 368),
    ('Irland', 'Ireland', 'ie', 'irl', 372),
    ('Insel Man', 'Isle of Man', 'im', 'imn', 833),
    ('', 'Israel', 'il', 'isr', 376),
    ('Italien', 'Italy', 'it', 'ita', 380),
    ('Jamaika', 'Jamaica', 'jm', 'jam', 388),
    ('', 'Japan', 'jp', 'jpn', 392),
    ('', 'Jersey', 'je', 'jey', 832),
    ('Jordanien', 'Jordan', 'jo', 'jor', 400),
    ('Kasachstan', 'Kazakhstan', 'kz', 'kaz', 398),
    ('', 'Kenya', 'ke', 'ken', 404),
    ('', 'Kiribati', 'ki', 'kir', 296),
    ('Korea, Demokratische Volksrepublik (Nord Korea)', 'Korea, Democratic People\'s Republic of', 'kp', 'prk', 408),
    ('Korea, Republik (Süd Korea)', 'Korea, Republic of', 'kr', 'kor', 410),
    ('', 'Kuwait', 'kw', 'kwt', 414),
    ('Kirgisistan', 'Kyrgyzstan', 'kg', 'kgz', 417),
    ('Laos, Demokratische Volksrepublik', 'Lao People\'s Democratic Republic', 'la', 'lao', 418),
    ('Lettland', 'Latvia', 'lv', 'lva', 428),
    ('Libanon', 'Lebanon', 'lb', 'lbn', 422),
    ('', 'Lesotho', 'ls', 'lso', 426),
    ('', 'Liberia', 'lr', 'lbr', 430),
    ('Libyen', 'Libyan Arab Jamahiriya', 'ly', 'lby', 434),
    ('', 'Liechtenstein', 'li', 'lie', 438),
    ('Litauen', 'Lithuania', 'lt', 'ltu', 440),
    ('Luxemburg', 'Luxembourg', 'lu', 'lux', 442),
    ('Macau', 'Macao', 'mo', 'mac', 446),
    ('Mazedonien', 'Macedonia, The former Yugoslav Republic of', 'mk', 'mkd', 807),
    ('Madagaskar', 'Madagascar', 'mg', 'mdg', 450),
    ('', 'Malawi', 'mw', 'mwi', 454),
    ('', 'Malaysia', 'my', 'mys', 458),
    ('Malediven', 'Maldives', 'mv', 'mdv', 462),
    ('', 'Mali', 'ml', 'mli', 466),
    ('', 'Malta', 'mt', 'mlt', 470),
    ('Marshallinseln', 'Marshall Islands', 'mh', 'mhl', 504),
    ('', 'Martinique', 'mq', 'mtq', 584),
    ('Mauretanien', 'Mauritania', 'mr', 'mrt', 478),
    ('', 'Mauritius', 'mu', 'mus', 480),
    ('', 'Mayotte', 'yt', 'myt', 175),
    ('Mexiko', 'Mexico', 'mx', 'mex', 484),
    ('Mikronesien, Föderierte Staaten von', 'Micronesia, Federated States of', 'fm', 'fsm', 583),
    ('Moldau, Republik', 'Moldova, Republic of', 'md', 'mda', 498),
    ('', 'Monaco', 'mc', 'mco', 492),
    ('Mongolei', 'Mongolia', 'mn', 'mng', 496),
    ('', 'Montenegro', 'me', 'mne', 499),
    ('', 'Montserrat', 'ms', 'msr', 500),
    ('Marokko', 'Morocco', 'ma', 'mar', 504),
    ('Mosambik', 'Mozambique', 'mz', 'moz', 508),
    ('', 'Myanmar', 'mm', 'mmr', 104),
    ('', 'Namibia', 'na', 'nam', 516),
    ('', 'Nauru', 'nr', 'nru', 520),
    ('', 'Nepal', 'np', 'npl', 524),
    ('Niederlande', 'Netherlands', 'nl', 'nld', 528),
    ('Neukaledonien', 'New Caledonia', 'nc', 'ncl', 540),
    ('Neuseeland', 'New Zealand', 'nz', 'nzl', 554),
    ('', 'Nicaragua', 'ni', 'nic', 558),
    ('', 'Niger', 'ne', 'ner', 562),
    ('', 'Nigeria', 'ng', 'nga', 566),
    ('', 'Niue', 'nu', 'niu', 570),
    ('Norfolkinsel', 'Norfolk Island', 'nf', 'nfk', 574),
    ('Nördliche Marianen', 'Northern Mariana Islands', 'mp', 'mnp', 580),
    ('Norwegen', 'Norway', 'no', 'nor', 578),
    ('', 'Oman', 'om', 'omn', 512),
    ('', 'Pakistan', 'pk', 'pak', 586),
    ('', 'Palau', 'pw', 'plw', 585),
    ('Palästinensische Autonomiegebiete', 'Palestinian Territory, Occupied', 'ps', 'pse', 275),
    ('', 'Panama', 'pa', 'pan', 591),
    ('Papua-Neuguinea', 'Papua New Guinea', 'pg', 'png', 598),
    ('', 'Paraguay', 'py', 'pry', 600),
    ('', 'Peru', 'pe', 'per', 604),
    ('Philippinen', 'Philippines', 'ph', 'phl', 608),
    ('Pitcairninseln', 'Pitcairn', 'pn', 'pcn', 612),
    ('Polen', 'Poland', 'pl', 'pol', 616),
    ('', 'Portugal', 'pt', 'prt', 620),
    ('', 'Puerto Rico', 'pr', 'pri', 630),
    ('Katar', 'Qatar', 'qa', 'qat', 634),
    ('Réunion', 'Reunion', 're', 'reu', 638),
    ('Rumänien', 'Romania', 'ro', 'rou', 642),
    ('Russische Föderation (Russland)', 'Russian Federation', 'ru', 'rus', 643),
    ('Ruanda', 'Rwanda', 'rw', 'rwa', 646),
    ('', 'Saint Barthelemy', 'bl', 'blm', 652),
    ('St. Helena', 'Saint Helena, Ascension and Tristan Da Cunha', 'sh', 'shn', 654),
    ('St. Kitts und Nevis', 'Saint Kitts and Nevis', 'kn', 'kna', 659),
    ('St. Lucia', 'Saint Lucia', 'lc', 'lca', 662),
    ('', 'Saint Martin (French Part)', 'mf', 'maf', 663),
    ('St. Pierre und Miquelon', 'Saint Pierre and Miquelon', 'pm', 'spm', 666),
    ('St. Vincent und die Grenadinen', 'Saint Vincent and The Grenadines', 'vc', 'vct', 670),
    ('', 'Samoa', 'ws', 'wsm', 882),
    ('', 'San Marino', 'sm', 'smr', 674),
    ('São Tomé und Príncipe', 'Sao Tome and Principe', 'st', 'stp', 678),
    ('Saudi-Arabien', 'Saudi Arabia', 'sa', 'sau', 682),
    ('', 'Senegal', 'sn', 'sen', 686),
    ('Serbien', 'Serbia', 'rs', 'srb', 688),
    ('Seychellen', 'Seychelles', 'sc', 'syc', 690),
    ('', 'Sierra Leone', 'sl', 'sle', 694),
    ('Singapur', 'Singapore', 'sg', 'sgp', 702),
    ('', 'Sint Maarten (Dutch Part)', 'sx', 'sxm', 534),
    ('Slowakei', 'Slovakia', 'sk', 'svk', 703),
    ('Slowenien', 'Slovenia', 'si', 'svn', 705),
    ('Salomonen', 'Solomon Islands', 'sb', 'slb', 90),
    ('', 'Somalia', 'so', 'som', 706),
    ('Südafrika', 'South Africa', 'za', 'zaf', 710),
    ('Südgeorgien und die südlichen Sandwichinseln', 'South Georgia and The South Sandwich Islands', 'gs', 'sgs', 239),
    ('Südsudan', 'South Sudan', 'ss', 'ssd', 728),
    ('Spanien', 'Spain', 'es', 'esp', 724),
    ('', 'Sri Lanka', 'lk', 'lka', 144),
    ('', 'Sudan', 'sd', 'sdn', 729),
    ('Suriname', 'Suriname', 'sr', 'sur', 740),
    ('Svalbard und Jan Mayen', 'Svalbard and Jan Mayen', 'sj', 'sjm', 744),
    ('Swasiland', 'Swaziland', 'sz', 'swz', 748),
    ('Schweden', 'Sweden', 'se', 'swe', 752),
    ('Schweiz', 'Switzerland', 'ch', 'che', 756),
    ('Syrien, Arabische Republik', 'Syrian Arab Republic', 'sy', 'syr', 760),
    ('Taiwan', 'Taiwan, Province of China', 'tw', 'twn', 158),
    ('Tadschikistan', 'Tajikistan', 'tj', 'tjk', 762),
    ('Tansania, Vereinigte Republik', 'Tanzania, United Republic of', 'tz', 'tza', 834),
    ('', 'Thailand', 'th', 'tha', 764),
    ('', 'Timor-Leste', 'tl', 'tls', 626),
    ('', 'Togo', 'tg', 'tgo', 768),
    ('', 'Tokelau', 'tk', 'tkl', 772),
    ('', 'Tonga', 'to', 'ton', 776),
    ('Trinidad und Tobago', 'Trinidad and Tobago', 'tt', 'tto', 780),
    ('Tunesien', 'Tunisia', 'tn', 'tun', 788),
    ('Türkei', 'Turkey', 'tr', 'tur', 792),
    ('', 'Turkmenistan', 'tm', 'tkm', 795),
    ('Turks- und Caicosinseln', 'Turks and Caicos Islands', 'tc', 'tca', 796),
    ('', 'Tuvalu', 'tv', 'tuv', 798),
    ('', 'Uganda', 'ug', 'uga', 800),
    ('', 'Ukraine', 'ua', 'ukr', 804),
    ('Vereinigte Arabische Emirate', 'United Arab Emirates', 'ae', 'are', 784),
    ('Großbritannien', 'United Kingdom', 'gb', 'gbr', 826),
    ('Vereinigte Staaten (USA)', 'United States', 'us', 'usa', 840),
    ('Kleinere Amerikanische Überseeinseln', 'United States Minor Outlying Islands', 'um', 'umi', 581),
    ('', 'Uruguay', 'uy', 'ury', 858),
    ('Usbekistan', 'Uzbekistan', 'uz', 'uzb', 860),
    ('', 'Vanuatu', 'vu', 'vut', 548),
    ('Venezuela', 'Venezuela, Bolivarian Republic of', 've', 'ven', 862),
    ('Vietnam', 'Viet Nam', 'vn', 'vnm', 704),
    ('Britische Jungferninseln', 'Virgin Islands, British', 'vg', 'vgb', 92),
    ('Amerikanische Jungferninseln', 'Virgin Islands, U.S.', 'vi', 'vir', 850),
    ('Wallis und Futuna', 'Wallis and Futuna', 'wf', 'wlf', 876),
    ('Westsahara', 'Western Sahara', 'eh', 'esh', 732),
    ('Jemen', 'Yemen', 'ye', 'yem', 887),
    ('Sambia', 'Zambia', 'zm', 'zmb', 894),
    ('Simbabwe', 'Zimbabwe', 'zw', 'zwe', 716)
